### ISSUE TITLE
mummer coordinates plot

### ISSUE THREAD

**Issue by Homap** [MariaNattestad/Ribbon#1]
Dear Maria,

Thank you for the great software. 

In the plot generated by using mummer coordinates in genome ribbon, is there a way to increase the intensity of color of the lines between the two sequences?

Thank you,
Best,
Homa

**Comment by MariaNattestad** [comment]
Hi Homa

Thank you for trying out Ribbon. 
I can definitely do that, but I want to make sure I understand what you are asking. 
Do you mean for the dot plot like this one?:
![ribbon single-read dot plot](https://cloud.githubusercontent.com/assets/7958077/19244395/062e83c8-8ed1-11e6-8bfa-686bb0810acb.png)

And do you want to increase the intensity of the dividing lines between pieces of the reference, or for the alignments themselves? 
Also, is it the thickness of the lines you are referring to or the actual color of the lines?

Thanks!
Maria

**Comment by MariaNattestad** [comment]
I think I know which lines you mean. I made the vertical lines darker between reference blocks in the dot plot. The website and version on github are updated with this change now. 
Let me know if that was what you were looking for. 

Thanks!
Maria

**Comment by Homap** [comment]
Dear Maria,

Thank you for your quick reply. 

Actually, I would like to visualise the rearrangements in one chromosome  between two species. Using nucmer output, I generated the following plot by GenomeRibbon by uploading the nucmer coordinate file. What I would like to do is to make the lines that connect the upper and lower horizontal bars ticker with a darker color (for example it can be done if the sequence similarity is above a certain threshold) as in the current output, it is not very easy to see, especially in power point presentation as the lines are not very strong in color even using color scheme three. Maybe I am using the programme in a wrong way.

![ribbon](https://cloud.githubusercontent.com/assets/7162756/19245730/008fb700-8f23-11e6-83cb-bb31741eee42.png)

Another point I was wondering about is whether it is possible to set lines with different coordinates in different colours, for example, if I want to put connecting lines between 1 to 20 megabase in green and 20 to 40 in blue for some underlying biological reason. 

Thank you again for your help and the software,
Cheers,
Homa

**Comment by MariaNattestad** [comment]
Hi Homa

Okay, now I see what you mean. The lines are very thin because there are only very small alignments between these two sequences. To highlight the alignments better, you can add outlines by going to the "Single-read settings" panel on the right side, clicking on the "settings" tab, and checking the box "Alignment outlines on ribbon plot." This will give you outlines for all of the alignments. If that looks too messy, you can use the "Filter alignments" tab to turn up the "Minimum % identity" or the "Minimum alignment length." The outlines used to be black, but I just tested changing them to the same color as the alignments, and that makes it clearer and prettier, so I will keep it that way. 
Let me know if this helps. 

For your other point about coloring by coordinates, that is not possible to do as of right now, but I can consider including it in the future if it is a feature that other people ask for too. 

Thanks!
Maria
