### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by sjackman** [MariaNattestad/Ribbon#12]
Hi, Maria. Bandage is astonishingly useful to me for visualizing misassemblies. Thanks for this tool!

I have a SAM or BAM file, and I'd like to programatically save an image of the top and bottom images, the bottom one a dot plot of a specified query sequence (or each of the query sequences, I'll have about ten or so). I'd like to upload the SAM/BAM file to http://genomeribbon.com using `curl --upload-file` and download a PNG/SVG/PDF. Alternatively a local installation of GenomeRibbon with a command line interface would work equally well. Any suggestions?

**Comment by MariaNattestad** [comment]
Hi Shaun. I hope you mean Ribbon, not Bandage :) though I'm sure Bandage is very useful too...
Ribbon does have an automated way to take pictures of the top and bottom plots. It works by going through every row in a BEDPE file, and it has to be for the same sam/bam file. You would load your BAM file and any features like genes or repeatMasker annotation (bed format) that you want, and then it will go through each row in the BEDPE file and take pictures. You can find this in the **Advanced Settings** in the navigation bar.

Since Ribbon is entirely client-side it's impossible to upload files to it, but it sounds like the existing automation may cover your use case. 

Note: It has to be a BEDPE file (because the automation was a quick hacky feature addition to help with Sniffles variant-call curation), but you can make both sides the same coordinate if you only need a single location.

Does that help?

**Comment by sjackman** [comment]
Haha! 😳 Sorry! Yes, Ribbon.

**Comment by sjackman** [comment]
> Since Ribbon is entirely client-side it's impossible to upload files to it

I did not know that. Cool!

> Ribbon does have an automated way to take pictures of the top and bottom plots.

Great! Thanks. After playing with it a bit, it seems like it selects a specified number of queries randomly from those that span either breakpoint and have split alignments. I would like to select all queries (in my case contig alignments), whether they're split or not, within a specified region. Although getting a figure for each read automated would be awesome, it's not critical.

I would like to be able to automate `Download top view as png` from the command line. That is, load a BAM and BAI file, select a region specified in a BED file, and save the top view to a PNG. Is that possible?

**Comment by sjackman** [comment]
I'm having trouble interactively selecting a region to display. Specifying a single position in `Select position` work as expected. Specifying a range such as `1:4000000-4100000` gives `Error: start value: could not be made into a number`.

I tried using `Upload variants` then selecting a BED file containing that region. It displays a split view showing the query spanning `1:4000000` and the query spanning `1:4100000` but not the queries in between. Any way to achieve that?

**Comment by MariaNattestad** [comment]
When you specify a position, it will grab all the reads within a certain distance of that position, which is specified in the Advanced Settings. You can't specify a range, but you could do 1:4050000 and set the distance in the Advanced Settings to 50000. This is not usually a good idea since it crashes if you load too many reads into memory at once, so beware. 

You can only do the automation with a BEDPE file, not a BED file, but you can just turn your BED file into a BEDPE file. The instructions in Advanced Settings under automation tell you how the automation works. It does take pictures of individual reads automatically. You can say how many reads you want to grab, so if you want all of them, just make it like 200.

**Comment by sjackman** [comment]
I'll try out the Advanced Settings for the distance. That should do the trick. I'm looking at alignment of contigs to a reference, so even though the range is a meg, there's only a dozen or so query alignments. Thanks for your help, Maria!
