### ISSUE TITLE
about large bam file

### ISSUE THREAD

**Issue by shunhuahan** [MariaNattestad/Ribbon#2]
Hi Maria,

I tried to use Ribbon to visualize a large bam file from sniffle (22GB) with lots of structure variants, I uploaded the bam (with index) and bedpe files. But the fetching process for each location is more than several hours and I haven't been able to visualize any of them. I am aware that the file size may cause this problem, but do you have any suggestions for that issue? Is the only way I should do is to reduce the size and filter out unwanted reads?

Thanks!

**Comment by MariaNattestad** [comment]
I have seen interesting issues with some specific bam files before, and these are hard to solve because Ribbon relies on the outside bam.iobio library for reading bam files, so I don't have direct control over how it reads bam files. For instance, one issue was that it doesn't work to have too many @PG header lines, but I have no idea why. I figured this out by experimenting with splicing together bam files that were working and not working, sort of an old-school genetic rescue experiment. All that is to say that I can help you figure out why the bam library doesn't work with your file if you give me access to the bam file, or a smaller piece of it that still has the same issue if you are more comfortable sharing that. The size of the bam file is not necessarily the issue, since I regularly run Ribbon with bam files over 300GB.
