### ISSUE TITLE
Scale chromosomes by size when viewing coordinates?

### ISSUE THREAD

**Issue by conte1** [MariaNattestad/Ribbon#25]
Let me first just say how useful this tool has been for our research.

I'm curious if there is a way to scale chromosomes by size when viewing MUMmer alignments? Currently both the top and bottom chromosomes are displayed with the same size horizontally even if they differ in size. We have several cases where a chromosome in one species is vastly larger than the corresponding chromosome in another species. It would be nice to be able to display the size difference when viewing the alignments. I don't think this is currently possible?

**Comment by MariaNattestad** [comment]
That would be a great idea, but it is unfortunately not currently possible in Ribbon. I won't have bandwidth to add it myself for the foreseeable future, but I could review a pull request if someone wants to contribute that change. Since you are working with MUMmer alignments, another tool I made called Dot might also be useful: https://github.com/MariaNattestad/Dot
