### ISSUE TITLE
Loading PacBio data

### ISSUE THREAD

**Issue by plurie** [MariaNattestad/Ribbon#32]
Hi,
I would really like to use ribbon to visualize my structural variants, but when I load the BAM and choose a location, I get back there are no reads in this location. I mapped PacBio files with NGMLR and they have a QNAME that follows this format @ /<ZMW_number>/_, but they do not include the chromosome. In your example you used PacBio alignments and did not have any problems, how did you get these to work? I've tried multiple aligners and the mapped BAM files always have the PACBIO BAM format as oppose to the conventional format.

**Comment by MariaNattestad** [comment]
The QNAME isn't used for fetching reads, so when you choose a location, it should match the chromosome, meaning RNAME in the BAM.

What are you entering when choosing a location?
Can you include ones of the lines from the BAM that you were expecting to show up from this query? e.g. using `samtools view` with that same region you are trying to fetch reads from. If `samtools view` on that region doesn't work, then it won't work here either, since Ribbon uses samtools to fetch reads.
