### ISSUE TITLE
upload data from server 

### ISSUE THREAD

**Issue by jainy** [MariaNattestad/Ribbon#49]
Hi, 
I am interested in using Ribbon.  Would it be possible to upload the bam files from the server, if I host Ribbon in that server.  Now even if I host ribbon in a server it is asking for files from my laptop. Since these are huge files, I have trouble in downloading them. I am not able to host the bam files publicly as well. 

Thank you for your help! Please let me know if you need any other info.
Best,
Jainy

**Comment by robertaboukhalil** [comment]
One way to do this would be to mount the remote server onto your local filesystem using [sshfs](https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh). That way you'll have a folder on your local computer that points to the data on the server.

Another approach would be to use [X11 forwarding](https://www.cyberciti.biz/faq/apple-osx-mountain-lion-mavericks-install-xquartz-server) to let you ssh into your server and launch a browser from there so that when you select a local file on Ribbon, the local file system will be that of the server, not your computer.
