### ISSUE TITLE
how to remove expand regions from selected region

### ISSUE THREAD

**Issue by panxiaoguang** [MariaNattestad/Ribbon#51]
Thank you for your great tools. can you tell me how to remove expand regions from selected region. the red cycle part in the figure

![](https://i.imgtg.com/2022/08/19/KJ3VI.png)

**Comment by panxiaoguang** [comment]
figure link is :https://i.imgtg.com/2022/08/19/KJ3VI.png

**Comment by MariaNattestad** [comment]
Try this: "single-read settings" panel -> "Settings" tab -> uncheck "Match reference from region view".
Try that also in combination with "Multi-read settings" panel -> "Reference" tab -> "Collapse reference sequences within distance:" lower the value for this variable.
And otherwise just play around with the settings in general.
