### ISSUE TITLE
Bring SplitThreader into Ribbon

### ISSUE THREAD

**Issue by robertaboukhalil** [MariaNattestad/Ribbon#58]

**Comment by MariaNattestad** [comment]
I pretty much have SplitThreader transplanted into Ribbon now. Both are functional side by side in this branch of Ribbon: https://github.com/MariaNattestad/Ribbon/tree/add-splitthreader.

We still need to:
1. Make a better user experience for switching back and forth. Currently you just click SplitThreader or Ribbon in the top navigation bar, but I want to make it more obvious when switching modes.
2. Clean up the rest of the navigation bar which is currently only Ribbon-related. SplitThreader's navbar has not been moved yet. I'll brainstorm a better UX for the shared navbar, where both tools' navigation bars need some cleanup anyway.
3. Figure out where to connect Ribbon and SplitThreader, in terms of sending information between them. Previously SplitThreader would make a POST request to Ribbon to send all the VCF variants over there, but now we could simply copy the data between their variables. This shouldn't be difficult. I will take a look at that. There may also be other connection points to make, but variants are the most obvious since they are an input data type that both SplitThreader and Ribbon use.

**Comment by MariaNattestad** [comment]
I made issue #75 to track the extensions mentioned above, so I'll close this issue as done.
