### ISSUE TITLE
visualize complex structural variants

### ISSUE THREAD

**Issue by ywzhang071394** [MariaNattestad/Ribbon#86]
Hi,

Thank you for the nice tool.
I am planning to use Ribbon to visualize a complex varaint across chr1,3,5. The bedpe file was uploaded. However, I cannot find any botton to simutanously choose multiple rows to visualize the complex SVs.
Could you point out the setting? Thank you!

**Comment by ywzhang071394** [comment]
Also, is that possible to show haplotags in Ribbon?

**Comment by MariaNattestad** [comment]
If you load just one variant, it should pull in the other regions if any read alignments from the chosen variant also aligns across the other variants. If no reads are spanning that far, then you would just have to visualize them separately. But I'll consider making it possible to select multiple loci explicitly because that's a good idea!
For haplotags, yes that's on my list. Should be done soon!

**Comment by ywzhang071394** [comment]
Thank you, Maria!
Looking forward to the new features at next version!
